### ISSUE TITLE
Can't fatpack File::Spec

### ISSUE THREAD

**Issue by miyagawa** [dagolden/Path-Tiny#136]
related to #55 

I'm sure I talked about this on IRC before, but Path::Tiny requires File::Spec 3.40, which is newer than the ones shipped with most perls before 5.18, so it's not really fatpack friendly.

The majority of File::Spec are actually pure-perl, so moving the files from arch to pure-perl in fatlib actually makes fatpacking still possible, but thought I'd open this issue just for the sake of conversation.

**Comment by miyagawa** [comment]
* relax File::Spec requirement in Path::Tiny (not sure what 3.40 requirement was for)
* split PathTools distribution to File::Spec (pure perl) and Cwd (XS) - don't know how coupled they are together
* leave it as it is, and on my end, copy the File/Spec.pm and friends from arch to perl dir since they're pure perl.

**Comment by dagolden** [comment]
IIRC, PathTools and Cwd came together because of some circular dependency problem, which wound up really bad on a system without a compiler.

I don't recall exactly why 3.40. Possibly just laziness on my part at the time, having been burned by too many bugs.  I think the tests are good enough that I keep the 3.40 in prereqs, but remove it as a runtime requirement and then test on older Pathtools and see what breaks.

Most of the File::Spec dependency is canonpath() and some of the abs/rel stuff and maybe any bugs there can be worked around in Path::Tiny.

**Comment by dagolden** [comment]
Example of a 3.40 fix: https://rt.perl.org/Public/Bug/Display.html?id=111510

**Comment by dagolden** [comment]
Looking at PathTools Changes in more detail, I think most of the problem is changes in abs2rel.  Possibly vendoring that huge, gross sub might be enough to rely on older File::Spec.

Looking at the sub, it could probably be done more efficiently, too, but testing it confidently could be a PITA.
