### ISSUE TITLE
Tilde expands unnecessarily

### ISSUE THREAD

**Issue by xsawyerx** [dagolden/Path-Tiny#190]
The tilde expansion is similar to the shell, which is basically:

* Expand `~` to home directory. (`path("~")` -> `/home/sawyer`)
* Expand `~user` to `user`s home directory. (`path("~sawyer")` -> `/home/sawyer`)
* If `user` does not exist, it's a local directory by that name instead. (`path("~notauser")` -> `~notauser`)
* If the first element is a different directory, the second element, even with a tilde, is just a directory inside it. (`path("/tmp/","~")` or `path("/tmp/","~")` -> `/tmp/~`)

However, these rules do not allow one to expand a directory path with a beginning tilde in the current directory:

```
# Same
$ perl -MPath::Tiny -E'say path(".","~sawyer")'
/home/sawyer
```

I would have expected `"./~sawyer"` or `("./","~sawyer")` to be `~sawyer`.

Here's my shell performing this:

```
$ echo ./~sawyer
./~sawyer
```

**Comment by ap** [comment]
It really ought to return `./~sawyer` and not reduce it to `~sawyer`.

Otherwise the return value is not safe to pass down to interfaces that perform tilde expansion (such as Path::Tiny itself…).

**Comment by xdg** [comment]
The problem I see is that I don't think Path::Tiny *ever* preserves a leading `.` in the path.

More specifically, `File::Spec::canonpath` doesn't and Path::Tiny religiously canonicalizes paths *once* and then preserves canonicalization thereafter.  Passing `./~david` to `canonpath` will also return `~david`.

This may have to be "fixed" via documentation.  Was there a real-world problem associated with this bug?  Or did you just notice an edge case?  If the former, I'd like to treat this as an XY problem and figure out if there's an alternative.

**Comment by ap** [comment]
But File::Spec never does tilde expansion. So its behaviour correct on its own terms.

Path::Tiny does do it. So its behaviour is not.

The timing of the tilde expansion is just wrong, that’s all there is to it. Since `canonpath` treats tildes literally and has no concept of tilde expansion, looking for tildes in its *output* is simply incorrect.

> I'd like to treat this as an XY problem and figure out if there's an alternative.

File and directory names can contain literal tildes. Right now there is no way to refer to a directory (or file) literally named `~root` relative to the current directory: `path('.')->child('~root')` is just as broken as `path('./~root')`. It may be a perfidious name for a file, but it’s a valid one. Are you saying that Path::Tiny need not be able to work correctly for every legal input?

I cannot agree with that, myself. I hope it does at least promise not to fail on spaces in paths? 😛

**Comment by xdg** [comment]
I need to think about the implications of leaving in the leading dot directory, but I appreciate the PR to play with.

**Comment by ap** [comment]
The only thing I can think of is that `path('.')->children` can now return a mix of values with and without `./` prefix. But I can’t think of any file operations this would actually break. Am I missing something? It seems to only possibly matter for display purposes, for which an extra `->basename` call would now be required. But that is still a reasonable state of affairs compared to getting back a list that goes something like `qw( .ssh .bashrc .profile Mail bin /var/root )`, as is currently the case…
