### ISSUE TITLE
tempdir ignores TEMPLATE

### ISSUE THREAD

**Issue by gonzus** [dagolden/Path-Tiny#199]
```
$ perl -MPath::Tiny -E'my $d = Path::Tiny->tempdir(TEMPLATE => "/home/gdiethelm/tmp_XXXX"); say $d;'
/tmp/tmp_QDEu
```

This happens because internally `tempdir()` always passes `TMPDIR => 1`:
```
    375     my $temp = File::Temp->newdir( @$maybe_template, TMPDIR => 1, %$args );
```

Just getting rid of that second arg would fix this; the caller could always add `TMPDIR => 1` if they need it. I can provide a pull request if required / easier. Thanks!

**Comment by gonzus** [comment]
Might be same as / related to https://github.com/dagolden/Path-Tiny/issues/115.

**Comment by haarg** [comment]
I don't think this is strictly a bug, as it is documented that TMPDIR is enabled by default.  It would be more useful if passing a DIR option or a template with a directory disabled the default TMPDIR option.

**Comment by gonzus** [comment]
I still think it is a bug, since there is no way to specify a template outside `TMPDIR`; but that's semantics :-). Any solution that allows passing a directory outside `TMPDIR` works for me.

**Comment by gonzus** [comment]
Doh, I just realized I could pass `TMPDIR => 0` myself when calling `Path::Tiny->tempdir`.

I still think it is a bit unexpected the way it works by default now, but feel free to close this issue if you don't expect to fix it. If you do, I could provide a patch.

**Comment by xdg** [comment]
I think you're exploiting an [undocumented feature](https://metacpan.org/source/DAGOLDEN/File-Temp-0.2304/lib/File/Temp.pm#L1162-1190) (?!) of File::Temp with an absolute path in `TEMPLATE`.

In Path::Tiny, I can achieve what you want like this:

```
$ perl -MPath::Tiny -E'my $d = Path::Tiny->tempdir(TEMPLATE => "tmp_XXXX", DIR => "$ENV{HOME}"); say $d;'
/Users/david/tmp_6zrd
```

Do you think it would be sufficient to document that absolute `TEMPLATE` isn't supported?  Or do you think we ought to detect an absolute `TEMPLATE` and omit `TMPDIR` in that case?

**Comment by ap** [comment]
It would be nice if one could write that as `path('~')->tempdir( 'tmp_XXXX' )`. But that already means the same thing as `Path::Tiny->tempdir( 'tmp_XXXX' )`, so too bad.

The whole design of exposing File::Temp directly but trying to sanitise its terrible interface seems… bad. I’d’ve written the method to take a single required argument for the template (with directories prohibited) and an optional options hash for setting `cleanup`; when called as a class method it would always use `File::Temp->tmpdir` as the base, otherwise itself. That would be a nicely Path::Tiny-ish design.

But enough with the fantasies… given where we are, my vote is a simple doc patch:

````diff
--- i/lib/Path/Tiny.pm
+++ w/lib/Path/Tiny.pm
@@ -315,7 +315,8 @@ sub rootdir { path( File::Spec->rootdir ) }
     $temp = tempdir( @options );  # optional export

 C<tempfile> passes the options to C<< File::Temp->new >> and returns a C<Path::Tiny>
-object with the file name.  The C<TMPDIR> option is enabled by default.
+object with the file name.  The C<TMPDIR> option will be enabled unless you
+turn it off.

 The resulting C<File::Temp> object is cached. When the C<Path::Tiny> object is
 destroyed, the C<File::Temp> object will be as well.
````

Strictly speaking the documentation is already correct and complete, but the implication of that “by default” is probably not explicit enough.
