### ISSUE TITLE
Implement new move/copy/rename interface

### ISSUE THREAD

**Issue by dagolden** [dagolden/Path-Tiny#58]
Following discussions in #22 I sketched out a plan to significantly revise how move/copy/rename work.  This issue is a placeholder to remind me to finish that work.

**Comment by kbenson** [comment]
@tobyink The gist I got from the (very in-depth) discussion on other issue was that copy/move of directories is where all the pain lies, and why this isn't just done already.

I second (or propose, if I slightly misunderstood from the prior discussion) the idea of handling copy/move of files as expected, and copy/move of directories when the dest is empty, and punting with some examples of how to use an iterator to implement your own behavior for move/copy of directories to paths where there is something present (be it file or directory).

Make simple things just work as expected, and inherently complex things (should moving/copying one directory over another merge, overwrite or use some complex heuristic for what to do on a file by file basis?) simpler.

**Comment by dagolden** [comment]
I know what I want to implement but mostly I've stalled on how to write tests for this in a way that actually tests the possible behaviors across file systems and such.

**Comment by regina-verbae** [comment]
What are you planning for the case where $src is a file and $dest is a directory?
a) fail
b) File::Copy behavior:
$src->[move|copy]($dest->child($src->basename))

My interpretation of all the previous discussion would suggest you're leaning toward (a).  If that's correct, is there a reason you don't like the behavior of File::Copy?

**Comment by regina-verbae** [comment]
I didn't see a certain resolution about whether you'll require a 'force' option in order for move to overwrite non-empty files/directories.

I personally agree with @schwern that the overwrite intent is clear.

It is pretty simple for a user to add a check if they want to protect against an overwrite.  You could make it even more straightforward by adding an 'empty' (or 'is_empty') method:

```perl
sub is_empty {
    my $self = shift;
    # Throw error if !$self->exists?
    return $self->is_dir ? not $self->iterator->() : not $self->stat->size;
}
```

Then this works whether $src is a file or directory:
`$src->move($dest) if $dest->is_empty;`

**Comment by jomo666** [comment]
Really would be nice to have the File::Copy behaviour for the `move`. (aka, allow cross filesystem `mv`)

**Comment by ambs** [comment]
While changes are not planned, it would be great to stress out the cross device link issue in Path::Tiny documentation, not requiring the user to will dig the documentation of rename to understand why it is failing.

**Comment by xdg** [comment]
I've concluded that I'll never have time to finish this work. Closing in favor of the simpler #260.

**Comment by grr** [comment]
Neither Path::Tiny nor File::Copy mention that moving a directory to a different device will fail. Getting an error message of "Is a directory" isn't immediately clear either. Also, there should be a mention of how to accomplish it properly when source and destination are in the same device: `$source->move($destination->child($source->basename))`, or provide a `mv` function that provides semantics similar to the unix command to which most of us are familiar.

Since others have asked about this in the past, it's not exacly an uncommon task:

  * [File::Copy and moving directories across volumes](https://www.perlmonks.org/?node_id=728153)
  * [Moving directories](https://www.perlmonks.org/?node_id=19964)
  * [how to move the folder from one directory to another directory?](https://www.perlmonks.org/?node_id=1111520)
  * [Move Directory in perl](https://stackoverflow.com/questions/14016649/move-directory-in-perl)
  * [How to copy the folder from one directory to another in perl?](https://stackoverflow.com/questions/25544962/how-to-copy-the-folder-from-one-directory-to-another-in-perl)
